#!/usr/bin/env python3
"""Stage 3 of the historical-backlog publish pipeline: apply approved
publish-review decisions into the public data/papers.json.

Reads a decisions TSV produced (and possibly hand-edited) by
export_publish_review.py:

  - decision=approve     -> build a papers.json entry from the SQLite row's
                             AI-authored content and append it (skipped if
                             the PMID is already published), mark
                             published_to_site=1 in the DB
  - decision=reject       -> mark human_review_status=rejected, never
                             published; stays in the DB, reversible later
  - anything else (blank, needs_edit, typo) -> treated as needs_edit and
                             NOT published, to fail closed rather than
                             publish something nobody actually approved

title_ja comes from the SQLite row's ai_title_ja, generated by
process_batch.py -- assets/app.js uses it as the paper's displayed heading
in Japanese mode (distinct from summary_ja, which renders separately as a
description), so it is included for every published entry, matching all
65 pre-existing ones. jif_tier is set to "unknown" unless match_jif.py has
already populated the row's jif_tier column, consistent with the
explicit-absence-over-silent-omission convention used for the rest of the
site.

Usage:
    python3 scripts/publish_to_site.py \
      --decisions /path/to/gct-literature-data/data/processed/publish_review/<run_id>/decisions_<run_id>.tsv \
      --db-dir /path/to/gct-literature-data/data/master
"""
import argparse
import csv
import json
import pathlib
import sys
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCRIPTS_DIR = pathlib.Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from gct_db import connect, json_load, existing_shard_paths  # noqa: E402

PAPERS_PATH = ROOT / "data" / "papers.json"


def now_utc():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def today():
    return datetime.now(timezone.utc).date().isoformat()


def find_row_and_conn(shard_conns, pmid):
    for conn in shard_conns.values():
        row = conn.execute("SELECT * FROM papers WHERE pmid = ?", (pmid,)).fetchone()
        if row is not None:
            return dict(row), conn
    return None, None


def build_entry(row):
    entry = {
        "id": f"pmid-{row['pmid']}",
        "title": row["title"] or "",
        "title_ja": row.get("ai_title_ja") or "",
        "authors": json_load(row.get("authors")),
        "journal": row.get("journal_abbrev") or row.get("journal_title") or "",
        "year": row.get("publication_year"),
        "pmid": row["pmid"],
        "doi": row.get("doi") or "",
        "url": "",
        "tags": json_load(row.get("ai_tags")),
        "summary_en": row.get("ai_summary_en") or "",
        "summary_ja": row.get("ai_summary_ja") or "",
        "abstract": row.get("abstract") or "",
        "abstract_ja": row.get("ai_abstract_ja") or "",
        "added_at": today(),
        "jif_tier": row.get("jif_tier") or "unknown",
        "relevance_status": row.get("relevance_status") or "kept",
        "relevance_note": row.get("relevance_note") or row.get("ai_relevance_reason") or "",
        "relevance_reviewed_at": row.get("relevance_reviewed_at") or "",
    }
    return entry


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--decisions", type=pathlib.Path, required=True)
    parser.add_argument("--db-dir", type=pathlib.Path, required=True)
    parser.add_argument("--papers", type=pathlib.Path, default=PAPERS_PATH)
    parser.add_argument("--reject-pmids", default="",
                        help="Comma-separated PMIDs to reject, overriding the decisions file "
                             "(so a reviewer needn't hand-edit a TSV). Must all appear in it.")
    parser.add_argument("--hold-pmids", default="",
                        help="Comma-separated PMIDs to mark needs_edit (not published), same rules.")
    args = parser.parse_args()
    reject = {p.strip() for p in args.reject_pmids.split(",") if p.strip()}
    hold = {p.strip() for p in args.hold_pmids.split(",") if p.strip()}

    shard_paths = existing_shard_paths(args.db_dir)
    if not shard_paths:
        raise FileNotFoundError(f"No shard database files found under {args.db_dir}")
    shard_conns = {path: connect(path) for path in shard_paths}

    papers = json.loads(args.papers.read_text(encoding="utf-8")) if args.papers.is_file() else []
    existing_pmids = {str(p.get("pmid")) for p in papers if p.get("pmid")}

    with args.decisions.open(encoding="utf-8", newline="") as f:
        decisions = list(csv.DictReader(f, delimiter="\t"))

    listed = {(r.get("pmid") or "").strip() for r in decisions}
    if reject & hold:
        raise SystemExit(f"PMIDs given both to reject and hold: {sorted(reject & hold)}")
    if (reject | hold) - listed:
        # A typo'd PMID would otherwise silently leave that paper approved.
        raise SystemExit(f"PMIDs not in the decisions file: {sorted((reject | hold) - listed)}")

    reviewed_at = now_utc()
    counts = {"published": 0, "rejected": 0, "needs_edit": 0, "already_published": 0, "unknown_pmid": 0}
    for decision_row in decisions:
        pmid = decision_row.get("pmid", "").strip()
        decision = (decision_row.get("decision") or "").strip()
        note = (decision_row.get("note") or "").strip()
        if pmid in reject:
            decision, note = "reject", note or "rejected at review"
        elif pmid in hold:
            decision, note = "needs_edit", note or "held at review"

        row, conn = find_row_and_conn(shard_conns, pmid)
        if row is None:
            counts["unknown_pmid"] += 1
            continue

        if decision == "approve":
            if pmid in existing_pmids:
                counts["already_published"] += 1
                status = "approved"
            else:
                papers.append(build_entry(row))
                existing_pmids.add(pmid)
                counts["published"] += 1
                status = "approved"
            conn.execute(
                """UPDATE papers SET
                     human_review_status = ?, human_review_note = ?, human_reviewed_at = ?,
                     published_to_site = 1, published_at = ?
                   WHERE pmid = ?""",
                (status, note, reviewed_at, reviewed_at, pmid),
            )
        elif decision == "reject":
            counts["rejected"] += 1
            conn.execute(
                """UPDATE papers SET
                     human_review_status = 'rejected', human_review_note = ?, human_reviewed_at = ?
                   WHERE pmid = ?""",
                (note, reviewed_at, pmid),
            )
        else:
            counts["needs_edit"] += 1
            conn.execute(
                """UPDATE papers SET
                     human_review_status = 'needs_edit', human_review_note = ?, human_reviewed_at = ?
                   WHERE pmid = ?""",
                (note, reviewed_at, pmid),
            )

    args.papers.write_text(json.dumps(papers, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    for conn in shard_conns.values():
        conn.commit()

    print(json.dumps(counts, ensure_ascii=False, indent=2))
    print(f"wrote: {args.papers} ({len(papers)} total entries)")


if __name__ == "__main__":
    main()
